import { readFileSync } from "node:fs";
import { describe, expect, it } from "vitest";
import { normalizeAccountInput } from "../src/account/account";
import { parseOtpvaultExport } from "../src/exporters/otpvault";
import { Vault } from "../src/vault/vault";
import { asyncCodeOf } from "./helpers/errors";
import { makeDeps } from "./helpers/vault";

// Fixtures were generated by the pre-rename code with fake data. They pin the
// frozen crypto identifiers (record/keyslot/export AAD, recovery HKDF info).
const PASSWORD = "legacy-fixture-pw";
const RECOVERY_CODE = "K4N2-KSFE-ECYQ-QKBA-H196-TFVS-BBEZ-03AB";

const load = (name: string): Record<string, unknown> =>
  JSON.parse(readFileSync(new URL(`./fixtures/${name}`, import.meta.url), "utf8"));

function freshDeps() {
  const deps = makeDeps();
  for (const [k, v] of Object.entries(load("legacy-otp-vault-vault.json")))
    deps.storage.data.set(k, v);
  return { ...deps, trash: deps.storage };
}

const accounts = [
  normalizeAccountInput({
    secret: "JBSWY3DPEHPK3PXP",
    issuer: "GitHub",
    label: "me",
    domains: ["github.com"],
  }),
  normalizeAccountInput({
    secret: "GEZDGNBVGY3TQOJQ",
    issuer: "Bank",
    label: "you",
    type: "hotp",
    counter: 9,
  }),
  normalizeAccountInput({ secret: "MFRGGZDFMZTWQ2LK", type: "steam", label: "gamer" }),
];

async function expectLegacyContents(vault: Vault) {
  const listing = await vault.listAccounts();
  const byLabel = (l: string) => listing.accounts.find((a) => a.label === l)!;
  expect(listing.accounts).toHaveLength(3);
  expect(listing.groups.map((g) => g.name)).toEqual(["Work"]);
  expect(listing.unreadable).toEqual([]);
  expect(listing.indexDamaged).toBe(false);
  for (const expected of accounts) {
    const got = byLabel(expected.label);
    expect(got).toMatchObject(expected);
  }
  expect(byLabel("me").groupId).toBe(listing.groups[0]!.id);
  expect(byLabel("you").groupId).toBeUndefined();
  const trash = await vault.listTrash();
  expect(trash.map((t) => [t.issuer, t.label])).toEqual([["Trashed", "gone"]]);
}

describe("legacy otp-vault vault fixture", () => {
  it("unlocks with the password and lists accounts, group and trash", async () => {
    const vault = await Vault.unlockWithPassword(freshDeps(), PASSWORD);
    await expectLegacyContents(vault);
  });

  it("unlocks with the recovery code on a fresh copy", async () => {
    const { vault } = await Vault.unlockWithRecovery(freshDeps(), RECOVERY_CODE, "new-pass-123");
    await expectLegacyContents(vault);
  });

  it("rejects a wrong password", async () => {
    expect(await asyncCodeOf(Vault.unlockWithPassword(freshDeps(), "nope-nope"))).toBe(
      "wrong-password",
    );
  });
});

describe("legacy .otpvault export fixture", () => {
  it("parses to the known accounts and group names", async () => {
    const result = await parseOtpvaultExport(load("legacy-otp-vault-export.json"), PASSWORD);
    expect(result.accounts).toEqual(accounts);
    expect(result.issues).toEqual([]);
    expect(result.groups).toEqual(["Work"]);
    expect(result.groupNames).toEqual(["Work", undefined, undefined]);
  });

  it("rejects a wrong export password", async () => {
    const json = load("legacy-otp-vault-export.json");
    expect(await asyncCodeOf(parseOtpvaultExport(json, "nope-nope"))).toBe("wrong-password");
  });
});
